### ISSUE TITLE
'DataFrame' object has no attribute 'reshape' error in examples/01_using_deepsurvk.py

### ISSUE THREAD

**Issue by FoppeCrezee** [arturomoncadatorres/deepsurvk#81]
#### Describe the bug

Following the code of the examples/01_using_deepsurvk.py file, you encounter en error in line 91 when reshaping Y_train. 

#### Steps/code to reproduce
```
X_train, Y_train, E_train, = load_whas(partition='training')
X_test, Y_test, E_test = load_whas(partition='testing')

Y_scaler = StandardScaler().fit(Y_train.reshape(-1, 1))
```

A simple fix should be replacing:
```
Y_scaler = StandardScaler().fit(Y_train.reshape(-1, 1))
```
with:
```
Y_scaler = StandardScaler().fit(Y_train.values.reshape(-1, 1))
```

#### Expected results

Reshaped dataframe

#### Actual results
```
AttributeError                            Traceback (most recent call last)
<ipython-input-21-04b713b91b55> in <module>
      4 # X_test = X_scaler.transform(X_test)
      5 
----> 6 Y_scaler = StandardScaler().fit(Y_train.reshape(-1, 1))
      7 Y_train = Y_scaler.transform(Y_train)
      8 Y_test = Y_scaler.transform(Y_test)

C:\ProgramData\Anaconda3\envs\iknl-internship\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   5460             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5461                 return self[name]
-> 5462             return object.__getattribute__(self, name)
   5463 
   5464     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'reshape' 
```
#### Versions
* DeepSurvK version: 0.2.0
* Python version: 3.7
* Operating System: Windows 10 Enterprise
* sklearn: 0.23.2

**Comment by arturomoncadatorres** [comment]
This issue is caused because you are reading the data as a `pandas` DataFrame, which indeed does not have the attribute reshape:

```
X_train, Y_train, E_train, = load_whas(partition='training')
X_test, Y_test, E_test = load_whas(partition='testing')
```

Like you well state, in this case the best option would be to use the DataFrame values:

```
Y_scaler = StandardScaler().fit(Y_train.values.reshape(-1, 1))
```

If you read the data as a `numpy` array, there is no issue:

```
X_train, Y_train, E_train, = load_whas(partition='training', data_type='np')
X_test, Y_test, E_test = load_whas(partition='testing', data_type='np')
```

I will update the example notebook to make this explicit as well.

**Comment by arturomoncadatorres** [comment]
Notebook was updated in commit https://github.com/arturomoncadatorres/deepsurvk/commit/aa8befe5ce9dc2652f990ff28af087cffc0810ca

**Comment by coderlegion419** [comment]
The AttributeError: 'DataFrame' object has no attribute 'reshape' occurs in Python when trying to use the .reshape() method on a Pandas DataFrame, which doesn’t support it. This happens due to a misunderstanding between Pandas DataFrames and NumPy arrays. To fix this, you can convert the DataFrame into a NumPy array using .values before applying .reshape(). Alternatively, Pandas provides built-in methods like pivot_table and stack for reshaping. Ensuring correct DataFrame selection and method chaining can also prevent this error. checkt this [CoderLegion](https://coderlegion.com/367/resolved-attributeerror-dataframe-object-has-no-attribute-reshape).
